# -*- coding: utf-8 -*-
"""SentimentalAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMBeFFKMMSYu61bYEt1aelzS9TOUytKM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

import nltk

import pandas as pd
df = pd.read_csv("Reviews.csv")
df.head

df['Text'].values[1]

ax = df['Score'].value_counts().sort_index().plot(kind = 'bar', title = 'Count of Reviews by Stars', figsize = (10,5))
ax.set_xlabel('Star Rating')
plt.show()

df = df[['Text', 'Score']].dropna()

df = df[df['Score'] != 3]

df['Sentiment'] = df['Score'].apply(lambda x: 1 if x > 3 else 0)

positive_df = df[df['Sentiment'] == 1]
negative_df = df[df['Sentiment'] == 0]

sample_size = min(len(positive_df), len(negative_df), 50000)

positive_sample = positive_df.sample(sample_size, random_state=42)
negative_sample = negative_df.sample(sample_size, random_state=42)

df = pd.concat([positive_sample, negative_sample])
df = df.sample(frac=1, random_state=42)

print(df['Sentiment'].value_counts())

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df['Text'] = df['Text'].apply(clean_text)

x = df['Text']
y = df["Sentiment"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

vectorizer = TfidfVectorizer(max_features = 15000, ngram_range = (1,3))

x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

model = LogisticRegression(max_iter = 1000, class_weight = 'balanced')
model.fit(x_train_vec, y_train)

y_pred = model.predict(x_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)

ax = df['Score'].value_counts().sort_index().plot(kind = 'bar', title = 'Count of Reviews by Stars', figsize = (10,5))
ax.set_xlabel('Star Rating')
plt.show()

def predict_sentiment(review):

    review_vec = vectorizer.transform([review])

    prediction = model.predict(review_vec)[0]
    probabilities = model.predict_proba(review_vec)[0]

    negative_score = probabilities[0]
    positive_score = probabilities[1]

    sentiment = "Positive" if prediction == 1 else "Negative"

    return sentiment, positive_score, negative_score


review = input("Enter your review: ")
result = predict_sentiment(review)

print(f"Sentiment: {result[0]}, Positive Score: {result[1]:.3f}, Negative Score: {result[2]:.3f}")